---
- name: Playbook - Remove packages    # metadata
  hosts: planetexpress:!farnsworth  # we want to take the planetexpress group and remove farnsworth
  connection: ssh     # default is to use the connection plugin ssh.py
  gather_facts: yes   # default is yes

  tasks:                             # a list of what we want to do 
  - name: using apt to Remove packages  # metadata
    apt:                     # the module we want to run, apt.py
      pkg:
      - figlet       
      - cowsay        
      - bastet         
      state: absent       # parameter state has the value present
    become: yes              # elevate status to admin, sudo, enable, etc.

